from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass
from datetime import date, datetime, timedelta, time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


from .config import settings

AUDIT_PATH = Path(__file__).resolve().parents[1] / "data" / "ai_audit.jsonl"
AUDIT_PATH.parent.mkdir(parents=True, exist_ok=True)


def _writelog(record: Dict[str, Any]) -> None:
    record.setdefault("ts", datetime.utcnow().isoformat() + "Z")
    with AUDIT_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^\w\s一-龥ぁ-んァ-ヶー・】）)\-]", " ", s.lower())).strip()


def _tokens(s: str) -> set[str]:
    s = _norm(s)
    # split by spaces and Japanese punctuation bullets
    toks = re.split(r"[\s・/|,;:()\[\]{}]+", s)
    return {t for t in toks if t}


def jaccard(a: str, b: str) -> float:
    ta, tb = _tokens(a), _tokens(b)
    if not ta or not tb:
        return 0.0
    inter = len(ta & tb)
    union = len(ta | tb)
    return inter / union if union else 0.0


def parse_time_ranges(text: str) -> List[Tuple[time, time]]:
    # Find HH:MM-HH:MM ranges
    ranges: List[Tuple[time, time]] = []
    for m in re.finditer(r"(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})", text):
        h1, m1, h2, m2 = map(int, m.groups())
        try:
            t1 = time(hour=h1, minute=m1)
            t2 = time(hour=h2, minute=m2)
            if t1 < t2:
                ranges.append((t1, t2))
        except Exception:
            continue
    return ranges


@dataclass
class TaskLike:
    id: Optional[int]
    title: str
    priority: str = "M"
    estimate_hours: Optional[float] = None
    due_date: Optional[str] = None
    status: str = "todo"


def _ensure_sources(plan: Dict[str, Any]) -> Dict[str, Any]:
    # Ensure source and reason_summary exist on blocks/alerts
    if not isinstance(plan, dict):
        return plan
    for b in plan.get("blocks", []) or []:
        b.setdefault("source", "llm")
        b.setdefault("reason_summary", "Generated by engine")
    for a in plan.get("alerts", []) or []:
        a.setdefault("source", "rule")
        a.setdefault("reason_summary", "Guardrail or risk detected")
    return plan


def organize(payload: Dict[str, Any]) -> Dict[str, Any]:
    # If OpenAI configured, try LLM path first
    if settings.openai_enabled:
        try:
            from .llm_client import organize_with_openai
            res = organize_with_openai(payload)
            res["plan"] = _ensure_sources(res.get("plan") or {})
            res["engine"] = "openai"
            return res
        except Exception:
            # fall back to heuristic below
            pass
    # Inputs
    free_text = str(payload.get("free_text") or "")
    today_hours = float(payload.get("today_hours") or 0.0)
    dialog_entries: List[Dict[str, Any]] = list(payload.get("dialog_entries") or [])
    context = payload.get("context") or {}
    tasks_in = context.get("tasks") or []
    checkins_recent = context.get("checkins_recent") or []
    events_recent = context.get("events_recent") or []

    # Build task objects
    tasks: List[TaskLike] = [
        TaskLike(
            id=int(t.get("id")) if t.get("id") is not None else None,
            title=str(t.get("title") or ""),
            priority=str(t.get("priority") or "M").upper(),
            estimate_hours=(float(t.get("estimate_hours")) if t.get("estimate_hours") is not None else None),
            due_date=str(t.get("due_date")) if t.get("due_date") else None,
            status=str(t.get("status") or "todo"),
        )
        for t in tasks_in
    ]

    # Extract candidates from dialog and free text
    lines: List[str] = []
    for e in dialog_entries:
        v = str(e.get("text") or e.get("value") or e.get("content") or "").strip()
        if v:
            lines.extend([x.strip() for x in re.split(r"[\n\r]+", v) if x.strip()])
    if free_text:
        lines.extend([x.strip() for x in re.split(r"[\n\r]+", free_text) if x.strip()])

    new_titles: List[str] = []
    done_titles: List[str] = []
    defer_titles: List[str] = []
    constraints_text = free_text
    for ln in lines:
        n = _norm(ln)
        if n.startswith("完了") or n.startswith("done") or n.startswith("[x]"):
            done_titles.append(ln.replace("[x]", "").strip())
        elif n.startswith("延期") or n.startswith("defer"):
            defer_titles.append(ln)
        elif any(n.startswith(p) for p in ["新規", "new", "task:", "+", "追加"]):
            new_titles.append(ln.lstrip("+ ").replace("新規", "").replace("new", "").replace("task:", "").strip())
        else:
            # generic bullet-like line considered for new candidate when looks like a task
            if re.match(r"^[-・•]", ln) or len(ln) <= 60:
                new_titles.append(ln.lstrip("-・• ").strip())

    # Dedupe matching against existing tasks by Jaccard
    dedupe: List[Dict[str, Any]] = []
    add: List[Dict[str, Any]] = []
    update: List[Dict[str, Any]] = []
    done: List[Dict[str, Any]] = []
    defer: List[Dict[str, Any]] = []

    for title in new_titles:
        best: Tuple[float, Optional[TaskLike]] = (0.0, None)
        for t in tasks:
            sim = jaccard(title, t.title)
            if sim > best[0]:
                best = (sim, t)
        if best[0] >= 0.8 and best[1] is not None:
            dedupe.append({
                "source": f"dialog:{title}",
                "matched_task_id": best[1].id,
                "similarity": round(best[0], 2),
                "decision": "merge",
            })
            # optional: update title to a normalized one if longer
            if len(title) > len(best[1].title):
                update.append({"id": best[1].id, "title": title})
        else:
            add.append({"title": title, "priority": "M"})

    for title in done_titles:
        # find best match to mark done
        best: Tuple[float, Optional[TaskLike]] = (0.0, None)
        for t in tasks:
            sim = jaccard(title, t.title)
            if sim > best[0]:
                best = (sim, t)
        if best[0] >= 0.5 and best[1] is not None:
            done.append({"id": best[1].id})

    for title in defer_titles:
        best: Tuple[float, Optional[TaskLike]] = (0.0, None)
        for t in tasks:
            sim = jaccard(title, t.title)
            if sim > best[0]:
                best = (sim, t)
        if best[0] >= 0.5 and best[1] is not None:
            # defer by +1 day if due exists else +3 days
            defer.append({
                "id": best[1].id,
                "due_date": (
                    (date.fromisoformat(best[1].due_date) + timedelta(days=1)).isoformat()
                    if best[1].due_date else (date.today() + timedelta(days=3)).isoformat()
                ),
            })

    # Priority scoring
    def due_urgency(d: Optional[str]) -> float:
        if not d:
            return 0.0
        try:
            dd = date.fromisoformat(d)
        except Exception:
            return 0.0
        days = (dd - date.today()).days
        if days <= 0:
            return 2.0
        if days <= 2:
            return 1.5
        if days <= 7:
            return 1.0
        return 0.0

    def pri_base(p: str) -> float:
        return {"H": 3.0, "M": 2.0, "L": 1.0}.get(p.upper(), 2.0)

    scoring: List[Dict[str, Any]] = []
    candidates: List[TaskLike] = [t for t in tasks if t.status != "done"]
    # Include newly added (tentative) for planning too
    new_fake_ids_start = 10_000_000
    for i, a in enumerate(add):
        candidates.append(TaskLike(id=new_fake_ids_start + i, title=a["title"], priority=a.get("priority", "M")))

    for t in candidates:
        base = pri_base(t.priority) + due_urgency(t.due_date) + (0.2 if (t.estimate_hours or 0) >= 1.5 else 0.0)
        adj = 0.0
        reasons: List[Dict[str, Any]] = []
        # LLM-like adjustments (heuristics with reasons)
        if t.due_date:
            dd = date.fromisoformat(t.due_date)
            if (dd - date.today()).days <= 2:
                adj += 2.0
                reasons.append({"source": "llm", "reason_summary": "Due <=48h, urgency boost +2"})
        if re.search(r"part|続き|follow[- ]?up|review", t.title, re.I):
            adj += 0.5
            reasons.append({"source": "llm", "reason_summary": "Continuity value +0.5"})
        if re.search(r"blocked|依存|待ち", t.title, re.I):
            adj -= 1.0
            reasons.append({"source": "llm", "reason_summary": "Likely blocked -1"})
        adj = max(-2.0, min(2.0, adj))
        score = base + adj
        scoring.append({
            "task_id": t.id,
            "title": t.title,
            "S_base": round(base, 2),
            "S_adj": round(adj, 2),
            "S_total": round(score, 2),
            "reasons": reasons or [{"source": "rule", "reason_summary": "Base factors applied"}],
        })

    scoring.sort(key=lambda x: (-x["S_total"], x["title"]))

    # Build schedule within today_hours (+15%)
    blocks: List[Dict[str, Any]] = []
    alerts: List[Dict[str, Any]] = []
    advice = ""
    total_hours = 0.0
    target = today_hours
    limit = today_hours * 1.15 if today_hours > 0 else None

    # time grid 09:00-18:00, exclude constraints
    busy = parse_time_ranges(constraints_text)
    cur = time(9, 0)
    def add_time(t: time, h: float) -> time:
        minutes = int(h * 60)
        hh = (t.hour * 60 + t.minute + minutes)
        return time(hh // 60, hh % 60)

    consec = 0
    last_task = None
    for sc in scoring:
        if limit is not None and total_hours >= limit:
            break
        # estimate chunk 0.5-2.0h (default 1.0h if unknown)
        est = 1.0
        for t in candidates:
            if t.id == sc["task_id"]:
                est = max(0.5, min(2.0, float(t.estimate_hours or 1.0)))
                break
        # enforce consecutive blocks limit
        if last_task == sc["task_id"] and consec >= 2:
            continue
        # skip if adding exceeds limit too much
        if limit is not None and (total_hours + est) > limit + 1e-6:
            # maybe shrink to fit to boundary but not <0.5
            remain = max(0.0, limit - total_hours)
            if remain >= 0.5:
                est = remain
            else:
                continue

        # place on timeline avoiding busy slots
        start = cur
        end = add_time(start, est)
        # if intersects busy, push forward
        def intersects(a: time, b: time, r: Tuple[time, time]) -> bool:
            return not (b <= r[0] or a >= r[1])
        moved = False
        while any(intersects(start, end, r) for r in busy):
            # jump to end of the first intersecting busy slot
            for r in busy:
                if intersects(start, end, r):
                    start = r[1]
                    end = add_time(start, est)
                    moved = True
                    break
        if moved or end <= time(23, 59):
            # accept block
            blocks.append({
                "title": sc["title"],
                "task_id": sc["task_id"],
                "start": start.strftime("%H:%M"),
                "end": end.strftime("%H:%M"),
                "hours": round(est, 2),
                "source": "llm",
                "reason_summary": "Ranked by score and placed avoiding busy times",
            })
            total_hours += est
            cur = end
            if last_task == sc["task_id"]:
                consec += 1
            else:
                consec = 1
                last_task = sc["task_id"]

    if limit is not None and total_hours > limit + 1e-6:
        alerts.append({"code": "OVERLOAD", "message": f"Planned {total_hours:.1f}h exceeds {limit:.1f}h", "source": "rule", "reason_summary": "+15% guardrail"})

    # deadline risk alerts
    risky = []
    for t in candidates:
        if not t.due_date or t.status == "done":
            continue
        try:
            dd = date.fromisoformat(t.due_date)
        except Exception:
            continue
        if (dd - date.today()).days <= 2:
            # if not included in blocks, alert
            if not any(b.get("task_id") == t.id for b in blocks):
                alerts.append({
                    "code": "DEADLINE_RISK",
                    "message": f"Task #{t.id or '-'} due within 48h not scheduled: {t.title}",
                    "source": "rule",
                    "reason_summary": "48h rule",
                })
                risky.append(t.title)

    if risky:
        advice = "期限が迫るタスクの前倒しや、他タスクの延期を検討してください。"

    plan = {
        "total_hours": round(total_hours, 2),
        "blocks": blocks,
        "alerts": alerts,
        "advice": advice,
    }

    audit = {
        "scoring": scoring,
        "rejects": [],
    }

    # Write audit log
    _writelog({"source": "ai_engine", "reason_summary": "organize computed", "payload": {"plan": plan, "mut_counts": {"add": len(add), "update": len(update), "done": len(done), "defer": len(defer)}, "dedupe": dedupe}})

    return {
        "plan": _ensure_sources(plan),
        "mutations": {"add": add, "update": update, "done": done, "defer": defer},
        "dedupe": dedupe,
        "audit": audit,
        "engine": "heuristic",
    }


def apply_mutations(
    *,
    mutations: Dict[str, Any],
    apply_fn: Any,
    reason: str = "Applied by AI engine",
) -> Dict[str, Any]:
    """Apply mutations via provided `apply_fn(kind, payload)` callable.

    Ensures idempotency using a simple request id in the payload if present.
    Records audit lines.
    """
    results: Dict[str, Any] = {"applied": [], "errors": []}
    for kind in ("add", "update", "done", "defer"):
        for item in mutations.get(kind, []) or []:
            try:
                res = apply_fn(kind, item)
                results["applied"].append({"kind": kind, "item": item, "result": res})
                _writelog({"source": "ai_apply", "reason_summary": reason, "kind": kind, "item": item})
            except Exception as e:
                results.setdefault("errors", []).append({"kind": kind, "item": item, "error": str(e)})
                _writelog({"source": "ai_apply", "reason_summary": f"error: {e}", "kind": kind, "item": item})
    return results
